import { useState } from "react";

function Reports() {
  const [reportStatus, setReportStatus] = useState("");

  const handleGenerate = () => {
    setReportStatus("Report generated successfully");
  };

  const handleJSON = () => {
    const reportData = {
      case_id: "CASE-2026-001",
      total_evidence: 24,
      verified_evidence: 24,
      artifacts: 186,
      findings: 17,
      critical_findings: 2,
      high_findings: 5,
      investigation_priority: 78,
      evidence_integrity: "100%",
    };

    const blob = new Blob(
      [JSON.stringify(reportData, null, 2)],
      {
        type: "application/json",
      }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "CASE-2026-001-report.json";

    link.click();

    URL.revokeObjectURL(url);

    setReportStatus("JSON report exported");
  };

  const handlePDF = () => {
    setReportStatus(
      "PDF generation will be connected to the backend"
    );
  };

  return (
    <div className="reports-page">

      {/* HEADER */}

      <div className="reports-header">

        <div>

          <div className="reports-label">
            FORENSIC REPORTING
          </div>

          <h1>
            Investigation Reports
          </h1>

          <p>
            Generate and export a structured forensic investigation report.
          </p>

        </div>


        <div className="reports-case">

          <span>
            CASE
          </span>

          <strong>
            CASE-2026-001
          </strong>

        </div>

      </div>


      {/* REPORT STATUS */}

      {reportStatus && (

        <div className="report-status">

          <span>
            ✓
          </span>

          {reportStatus}

        </div>

      )}


      {/* CASE OVERVIEW */}

      <div className="report-overview">

        <div className="report-overview-main">

          <div className="report-overview-title">

            <span>
              INVESTIGATION REPORT
            </span>

            <h2>
              CASE-2026-001
            </h2>

            <p>
              ForensiX AI-Assisted Digital Forensic Investigation
            </p>

          </div>


          <div className="report-risk">

            <span>
              INVESTIGATION PRIORITY
            </span>

            <strong>
              78
            </strong>

            <small>
              HIGH PRIORITY
            </small>

          </div>

        </div>


        <div className="report-meta">

          <div>
            <span>REPORT STATUS</span>
            <strong>READY</strong>
          </div>

          <div>
            <span>EVIDENCE STATUS</span>
            <strong className="report-success">
              VERIFIED
            </strong>
          </div>

          <div>
            <span>CASE TYPE</span>
            <strong>
              DIGITAL FORENSICS
            </strong>
          </div>

          <div>
            <span>GENERATED BY</span>
            <strong>
              FORENSIX
            </strong>
          </div>

        </div>

      </div>


      {/* STATISTICS */}

      <div className="report-stats">

        <div className="report-stat">

          <span>
            TOTAL EVIDENCE
          </span>

          <strong>
            24
          </strong>

          <small>
            Collected items
          </small>

        </div>


        <div className="report-stat">

          <span>
            ARTIFACTS
          </span>

          <strong>
            186
          </strong>

          <small>
            Extracted artifacts
          </small>

        </div>


        <div className="report-stat">

          <span>
            FINDINGS
          </span>

          <strong>
            17
          </strong>

          <small>
            Detection results
          </small>

        </div>


        <div className="report-stat">

          <span>
            HIGH / CRITICAL
          </span>

          <strong className="report-danger">
            07
          </strong>

          <small>
            Requires attention
          </small>

        </div>

      </div>


      {/* REPORT CONTENT */}

      <div className="report-content-grid">


        {/* FINDINGS SUMMARY */}

        <section className="report-section">

          <div className="report-section-header">

            <div>

              <span>
                FINDINGS ANALYSIS
              </span>

              <h2>
                Detection Summary
              </h2>

            </div>

          </div>


          <div className="finding-summary-row">

            <div>
              <span className="summary-dot critical"></span>

              <div>
                <strong>Critical</strong>
                <small>2 findings</small>
              </div>

              <b>02</b>
            </div>


            <div>
              <span className="summary-dot high"></span>

              <div>
                <strong>High</strong>
                <small>5 findings</small>
              </div>

              <b>05</b>
            </div>


            <div>
              <span className="summary-dot medium"></span>

              <div>
                <strong>Medium</strong>
                <small>6 findings</small>
              </div>

              <b>06</b>
            </div>


            <div>
              <span className="summary-dot low"></span>

              <div>
                <strong>Low</strong>
                <small>4 findings</small>
              </div>

              <b>04</b>
            </div>

          </div>

        </section>


        {/* INTEGRITY */}

        <section className="report-section">

          <div className="report-section-header">

            <div>

              <span>
                EVIDENCE VALIDATION
              </span>

              <h2>
                Integrity Status
              </h2>

            </div>

          </div>


          <div className="integrity-report">

            <div className="integrity-icon">
              ✓
            </div>

            <div>

              <strong>
                100% VERIFIED
              </strong>

              <p>
                All collected evidence passed SHA-256
                integrity verification.
              </p>

            </div>

          </div>


          <div className="integrity-details">

            <div>
              <span>COLLECTED</span>
              <strong>24</strong>
            </div>

            <div>
              <span>VERIFIED</span>
              <strong>24</strong>
            </div>

            <div>
              <span>MISMATCH</span>
              <strong>00</strong>
            </div>

          </div>

        </section>


      </div>


      {/* REPORT SCOPE */}

      <section className="report-scope">

        <div>

          <span>
            REPORT SCOPE
          </span>

          <h2>
            Included Investigation Data
          </h2>

        </div>


        <div className="scope-items">

          <div>
            <span>✓</span>
            Evidence metadata
          </div>

          <div>
            <span>✓</span>
            Artifact analysis
          </div>

          <div>
            <span>✓</span>
            Detection findings
          </div>

          <div>
            <span>✓</span>
            Investigation timeline
          </div>

          <div>
            <span>✓</span>
            AI explanations
          </div>

          <div>
            <span>✓</span>
            Evidence integrity
          </div>

        </div>

      </section>


      {/* ACTIONS */}

      <section className="report-actions">

        <div>

          <span>
            REPORT GENERATION
          </span>

          <h2>
            Export Investigation Report
          </h2>

          <p>
            Generate a structured report containing the
            current investigation data.
          </p>

        </div>


        <div className="report-buttons">

          <button
            className="report-primary-button"
            onClick={handleGenerate}
          >
            Generate Report
          </button>


          <button
            className="report-secondary-button"
            onClick={handleJSON}
          >
            Export JSON
          </button>


          <button
            className="report-secondary-button"
            onClick={handlePDF}
          >
            Export PDF
          </button>

        </div>

      </section>


      {/* NOTE */}

      <div className="report-note">

        <strong>
          Report Note:
        </strong>

        {" "}
        Generated reports represent the current investigation
        state. AI-generated explanations are decision-support
        information and should be validated against the underlying
        forensic evidence.

      </div>

    </div>
  );
}

export default Reports;